### ISSUE TITLE
Version checking bug

### ISSUE THREAD

**Issue by DrHyde** [bigpresh/Net-Joker-DMAPI#4]
> Net::Joker::DMAPI 0.06 has not been tested with Joker DMAPI version 1.2 at
> /opt/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2/Net/Joker/DMAPI.pm
> line 297.

You appear to have a bug here:

    my ($dmapi_major_version) = $headers{Version} =~ /^(\d+\.\d+)\./;
    if ($dmapi_major_version ne '1.2') {
        warn __PACKAGE__ . " $VERSION has not been tested with Joker"
            . " DMAPI version $headers{Version}";
    }

$dmapi_major_version won't be set, because 1.2 doesn't match
^(\d+\.\d+)\. - the trailing \. probably shouldn't be there.

**Comment by DrHyde** [comment]
The bug appears to also be present in 0.07

**Comment by bigpresh** [comment]
This should be fixed in version 0.08, just released to CPAN.

As best I can tell, Joker's DMAPI version number went backwards, from 1.2.34 to just 1.2.  Yay.

**Comment by bigpresh** [comment]
Bingo: https://dmapi.joker.com/docs/dmapi-1.2.txt shows the most recent version as `1.2.38`, but they now return just 1.2 as the version number, it would seem.
